version: '3.8'

services:
  mongodb:
    container_name: mongodb
    image: mongo:5.0.2
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=supplychain
      - MONGO_INITDB_ROOT_USERNAME=supplychain
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - 27017:27017
    volumes:
      - ./.docker-resources/db:/data/db
    networks:
      - app-network

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs
    depends_on:
      - mongodb
    volumes:
      - ./:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge