export enum PartnerTypeEnum {
    PARTNER_WAREHOUSE = 'PARTNER_WAREHOUSE',
    PARTNER_SUPPLIER = 'PARTNER_SUPPLIER',
    PARTNER_RETAILER = 'PARTNER_RETAILER',
    PARTNER_DELIVER = 'PARTNER_DELIVER',
}